#ifndef ids_h
#define ids_h
#include "datatypes.h"
namespace Blocks { //0x00-0xbf
inline constexpr id_t air =            0x00;
inline constexpr id_t fire =           0x01;
inline constexpr id_t dirt =           0x02;
inline constexpr id_t cobblestone =    0x03;
inline constexpr id_t lava0 =          0x04;
inline constexpr id_t lava1 =          0x05;
inline constexpr id_t lava2 =          0x06;
inline constexpr id_t lava3 =          0x07;
inline constexpr id_t lavaSource =     0x08;
inline constexpr id_t water0 =         0x09;
inline constexpr id_t water1 =         0x0a;
inline constexpr id_t water2 =         0x0b;
inline constexpr id_t water3 =         0x0c;
inline constexpr id_t water4 =         0x0d;
inline constexpr id_t water5 =         0x0e;
inline constexpr id_t water6 =         0x0f;
inline constexpr id_t water7 =         0x10;
inline constexpr id_t waterSource =    0x11;
inline constexpr id_t dryFarmland =    0x12;
inline constexpr id_t farmland0 =      0x13;
inline constexpr id_t farmland1 =      0x14;
inline constexpr id_t farmland2 =      0x15;
inline constexpr id_t farmland3 =      0x16;
inline constexpr id_t wheat0 =         0x17;
inline constexpr id_t wheat1 =         0x18;
inline constexpr id_t wheat2 =         0x19;
inline constexpr id_t wheat3 =         0x1a;
inline constexpr id_t carrot0 =        0x1b;
inline constexpr id_t carrot1 =        0x1c;
inline constexpr id_t carrot2 =        0x1d;
inline constexpr id_t carrot3 =        0x1e;
inline constexpr id_t potato0 =        0x1f;
inline constexpr id_t potato1 =        0x20;
inline constexpr id_t potato2 =        0x21;
inline constexpr id_t potato3 =        0x22;
inline constexpr id_t coalOre =        0x23;
inline constexpr id_t ironOre =        0x24;
inline constexpr id_t goldOre =        0x25;
inline constexpr id_t diamondOre =     0x26;
inline constexpr id_t closedDoor =     0x27;
inline constexpr id_t openDoor =       0x28;
inline constexpr id_t closedTrapdoor = 0x29;
inline constexpr id_t openTrapdoor =   0x2a;
inline constexpr id_t stone =          0x2b;
inline constexpr id_t sandstone =      0x2c;
inline constexpr id_t gravel =         0x2d;
inline constexpr id_t sand =           0x2e;
inline constexpr id_t wood =           0x2f;
inline constexpr id_t planks =         0x30;
inline constexpr id_t leaves =         0x31;
inline constexpr id_t obsidian =       0x32;
inline constexpr id_t glass =          0x33;
inline constexpr id_t stoneBricks =    0x34;
inline constexpr id_t wool =           0x35;
inline constexpr id_t goldBlock =      0x36;
inline constexpr id_t bed =            0x37;
inline constexpr id_t ladder =         0x38;
inline constexpr id_t torch =          0x39;
inline constexpr id_t sponge =         0x3a;
inline constexpr id_t craftingTable =  0x3b;
inline constexpr id_t furnace =        0x3c;
inline constexpr id_t chest =          0x3d;
inline constexpr id_t grass =          0x3e;
inline constexpr id_t sapling =        0x3f;
inline constexpr id_t flower =         0x40;
inline constexpr id_t tnt =            0x41;
inline constexpr id_t litTnt =         0x42;

namespace Runtime { //0xc0-0xdf
inline constexpr id_t light0 = 0xc0;
inline constexpr id_t light1 = 0xc1;
inline constexpr id_t light2 = 0xc2;
inline constexpr id_t light3 = 0xc3;
inline constexpr id_t light4 = 0xc4;
inline constexpr id_t light5 = 0xc5;
inline constexpr id_t light6 = 0xc6;
inline constexpr id_t light7 = 0xc7;
inline constexpr id_t empty =  0xc8;
inline constexpr id_t error =  0xc9;
}
namespace Generation { //0xc0-ff
inline constexpr id_t air =        0xc0;
inline constexpr id_t tempAir =    0xc1;
inline constexpr id_t dirt =       0xc2;
inline constexpr id_t tempDirt =   0xc3;
inline constexpr id_t gravel =     0xc4;
inline constexpr id_t sand =       0xc5;
inline constexpr id_t tempSand =   0xc6;
inline constexpr id_t coalOre =    0xc7;
inline constexpr id_t ironOre =    0xc8;
inline constexpr id_t goldOre =    0xc9;
inline constexpr id_t diamondOre = 0xca;
inline constexpr id_t wood =       0xcb;
inline constexpr id_t tempWood =   0xcc;
inline constexpr id_t leaves =     0xcd;
inline constexpr id_t tempLeaves = 0xce;
inline constexpr id_t sandstone =  0xcf;
inline constexpr id_t grass =      0xd0;
}
namespace Update { //0xe0-0xff
inline constexpr id_t deletedWater0 =  0xe0;
inline constexpr id_t deletedWater1 =  0xe1;
inline constexpr id_t deletedWater2 =  0xe2;
inline constexpr id_t deletedWater3 =  0xe3;
inline constexpr id_t deletedWater4 =  0xe4;
inline constexpr id_t deletedWater5 =  0xe5;
inline constexpr id_t deletedWater6 =  0xe6;
inline constexpr id_t deletedWater7 =  0xe7;
inline constexpr id_t deletedLava0 =   0xe8;
inline constexpr id_t deletedLava1 =   0xe9;
inline constexpr id_t deletedLava2 =   0xea;
inline constexpr id_t deletedLava3 =   0xeb;
inline constexpr id_t deletedLava4 =   0xec;
inline constexpr id_t deletedLava5 =   0xed;
inline constexpr id_t deletedLava6 =   0xee;
inline constexpr id_t deletedLava7 =   0xef;
}
}
namespace Storage { //0xc0-ff
inline constexpr id_t threeByteFlag =  0xfa; //Indicates that the next 2 bytes are compressed
inline constexpr id_t fourByteFlag  =  0xfb; //Indicates that the next 3 bytes are compressed
inline constexpr id_t comma =          0xfc; //Separates two similar saved items, such as two chests or two mobs
inline constexpr id_t semicolon =      0xfd; //Separates two saving sections, such as pigs and zombies
inline constexpr id_t period =         0xfe; //Separates two world save sections, such as between blocks and items
inline constexpr id_t end =            0xff; //Will be deprecated once a map of the filesystem is added
}
namespace Items {
inline constexpr id_t none =               0x00;
inline constexpr id_t gunpowder =          0x01;
inline constexpr id_t dirt =               0x02;
inline constexpr id_t cobblestone =        0x03;
inline constexpr id_t wheat =              0x04;
inline constexpr id_t seeds =              0x05;
inline constexpr id_t carrot =             0x06;
inline constexpr id_t potato =             0x07;
inline constexpr id_t rottenFlesh =        0x08;
inline constexpr id_t ironOre =            0x09;
inline constexpr id_t goldOre =            0x0a;
inline constexpr id_t door =               0x0b;
inline constexpr id_t trapdoor =           0x0c;
inline constexpr id_t stone =              0x0d;
inline constexpr id_t sandstone =          0x0e;
inline constexpr id_t gravel =             0x0f;
inline constexpr id_t sand =               0x10;
inline constexpr id_t wood =               0x11;
inline constexpr id_t planks =             0x12;
inline constexpr id_t obsidian =           0x13;
inline constexpr id_t glass =              0x14;
inline constexpr id_t stoneBricks =        0x15;
inline constexpr id_t wool =               0x16;
inline constexpr id_t goldBlock =          0x17;
inline constexpr id_t bed =                0x18;
inline constexpr id_t ladder =             0x19;
inline constexpr id_t torch =              0x1a;
inline constexpr id_t sponge =             0x1b;
inline constexpr id_t craftingTable =      0x1c;
inline constexpr id_t furnace =            0x1d;
inline constexpr id_t chest =              0x1e;
inline constexpr id_t sapling =            0x1f;
inline constexpr id_t flower =             0x20;
inline constexpr id_t tnt =                0x21;
inline constexpr id_t woodSword =          0x22;
inline constexpr id_t woodPickaxe =        0x23;
inline constexpr id_t woodShovel =         0x24;
inline constexpr id_t woodAxe =            0x25;
inline constexpr id_t woodHoe =            0x26;
inline constexpr id_t stoneSword =         0x27;
inline constexpr id_t stonePickaxe =       0x28;
inline constexpr id_t stoneShovel =        0x29;
inline constexpr id_t stoneAxe =           0x2a;
inline constexpr id_t stoneHoe =           0x2b;
inline constexpr id_t goldSword =          0x2c;
inline constexpr id_t goldPickaxe =        0x2d;
inline constexpr id_t goldShovel =         0x2e;
inline constexpr id_t goldAxe =            0x2f;
inline constexpr id_t goldHoe =            0x30;
inline constexpr id_t ironSword =          0x31;
inline constexpr id_t ironPickaxe =        0x32;
inline constexpr id_t ironShovel =         0x33;
inline constexpr id_t ironAxe =            0x34;
inline constexpr id_t ironHoe =            0x35;
inline constexpr id_t diamondSword =       0x36;
inline constexpr id_t diamondPickaxe =     0x37;
inline constexpr id_t diamondShovel =      0x38;
inline constexpr id_t diamondAxe =         0x39;
inline constexpr id_t diamondHoe =         0x3a;
inline constexpr id_t bow =                0x3b;
inline constexpr id_t arrow =              0x3c;
inline constexpr id_t charcoal =           0x3d;
inline constexpr id_t coal =               0x3e;
inline constexpr id_t goldIngot =          0x3f;
inline constexpr id_t ironIngot =          0x40;
inline constexpr id_t diamond =            0x41;
inline constexpr id_t leatherHelmet =      0x42;
inline constexpr id_t leatherChestplate =  0x43;
inline constexpr id_t leatherLeggings =    0x44;
inline constexpr id_t leatherBoots =       0x45;
inline constexpr id_t goldHelmet =         0x46;
inline constexpr id_t goldChestplate =     0x47;
inline constexpr id_t goldLeggings =       0x48;
inline constexpr id_t goldBoots =          0x49;
inline constexpr id_t ironHelmet =         0x4a;
inline constexpr id_t ironChestplate =     0x4b;
inline constexpr id_t ironLeggings =       0x4c;
inline constexpr id_t ironBoots =          0x4d;
inline constexpr id_t diamondHelmet =      0x4e;
inline constexpr id_t diamondChestplate =  0x4f;
inline constexpr id_t diamondLeggings =    0x50;
inline constexpr id_t diamondBoots =       0x51;
inline constexpr id_t stick =              0x52;
inline constexpr id_t leather =            0x53;
inline constexpr id_t string =             0x54;
inline constexpr id_t bucket =             0x55;
inline constexpr id_t waterBucket =        0x56;
inline constexpr id_t lavaBucket =         0x57;
inline constexpr id_t rawChicken =         0x58;
inline constexpr id_t cookedChicken =      0x59;
inline constexpr id_t rawPork =            0x5a;
inline constexpr id_t cookedPorkchop =     0x5b;
inline constexpr id_t rawBeef =            0x5c;
inline constexpr id_t steak =              0x5d;
inline constexpr id_t bread =              0x5e;
inline constexpr id_t feather =            0x5f;
inline constexpr id_t flint =              0x60;
inline constexpr id_t flintAndSteel =      0x61;
}

#endif
